export const RAG_ORCHESTRATOR = 'RAG_ORCHESTRATOR';
export const DEFAULT_RAG_MAX_HOPS = 3;
export const DEFAULT_RAG_MAX_WEB_SEARCH_ATTEMPTS = 2;
export const DEFAULT_RAG_RETRY_INITIAL_INTERVAL_MS = 200;
export const DEFAULT_RAG_RETRY_BACKOFF_FACTOR = 2;
export const DEFAULT_RAG_RETRY_MAX_INTERVAL_MS = 1000;
